name: Test

on:
  # Run on pushes to `master` and on all pull requests.
  push:
    branches:
      - master
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  tests:
    name: PHP ${{ matrix.php }} with PHPCS ${{ matrix.phpcs_branch }}/WPCS ${{ matrix.wpcs_branch }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_failure }}
    strategy:
      fail-fast: false
      matrix:
        # Builds against PHP 7.2, 7.4 and 8.0 are specified separately in the "include" section below.
        php: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.3' ]
        phpcs_branch: [ '3.3.1', 'dev-master' ]
        wpcs_branch: [ '2.2.0', 'dev-master' ]
        allowed_failure: [ false ]
        exclude:
          # Only run low WPCS in combination with low PHPCS and high WPCS with high PHPCS.
          - phpcs_branch: 'dev-master'
            wpcs_branch: '2.2.0'
          - phpcs_branch: '3.3.1'
            wpcs_branch: 'dev-master'
        include:
          # Complete the matrix.
          # PHPCS 3.5.0 is the lowest PHPCS version (runtime) compatible with PHP 7.4.
          # PHPCS 3.5.7 is the lowest PHPCS version (runtime) compatible with PHP 8.0.
          - php: '7.4'
            phpcs_branch: 'dev-master'
            wpcs_branch: 'dev-master'
            allowed_failure: false
          - php: '7.4'
            phpcs_branch: '3.5.0'
            wpcs_branch: '2.3.0'
            allowed_failure: false
          - php: '8.0'
            phpcs_branch: 'dev-master'
            wpcs_branch: 'dev-master'
            allowed_failure: false
          - php: '8.0'
            phpcs_branch: '3.5.7'
            wpcs_branch: '2.3.0'
            allowed_failure: false

          # Compliment the matrix with some additional builds.
          # Separate test builds for PHP 7.2 with reversed PHPCS vs WPCS branches.
          - php: '7.2'
            phpcs_branch: 'dev-master'
            wpcs_branch: '2.2.0'
            allowed_failure: false
          - php: '7.2'
            phpcs_branch: '3.3.1'
            wpcs_branch: 'dev-master'
            allowed_failure: false

          # Experimental build to see how much breaks against WPCS 3.0.
          - php: '7.4'
            phpcs_branch: 'dev-master'
            wpcs_branch: 'dev-develop'
            allowed_failure: true

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # On stable PHPCS versions, allow for PHP deprecation notices.
      # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
      - name: Setup ini config
        id: set_ini
        run: |
          if [[ "${{ matrix.phpcs_branch }}" != "dev-master" && "${{ matrix.wpcs_branch }}" != "dev-develop" ]]; then
            echo '::set-output name=PHP_INI::error_reporting=E_ALL & ~E_DEPRECATED'
          else
            echo '::set-output name=PHP_INI::error_reporting=E_ALL'
          fi

      # Setup PHP versions, run checks
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: ${{ steps.set_ini.outputs.PHP_INI }}
          coverage: none

      - name: Set the minimum stability requirement for develop branch of WPCS
        if: ${{ matrix.wpcs_branch == 'dev-develop' }}
        run: composer config minimum-stability dev

      - name: Set the required PHPCS and WPCS versions
        env:
          PHPCS_BRANCH: ${{ matrix.phpcs_branch }}
          WPCS_BRANCH: ${{ matrix.wpcs_branch }}
        run: composer require squizlabs/php_codesniffer:${PHPCS_BRANCH} wp-coding-standards/wpcs:${WPCS_BRANCH} --no-update --no-scripts

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        if: ${{ matrix.php < 8.0 }}
        uses: ramsey/composer-install@v1

      - name: Install Composer dependencies
        if: ${{ matrix.php >= 8.0 }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: --ignore-platform-reqs

      - name: Run tests
        run: composer run-tests
